# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Cvuorinen.net
description: Dev notes & thoughts about web development
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://cvuorinen.net" # the base hostname & protocol for your site
logo: "apple-touch-icon.png"
twitter_username: cvuorinen
github_username:  cvuorinen
google_analytics: "UA-35040029-1"

# Build settings
markdown: kramdown
highlighter: rouge
permalink: /:year/:month/:title/
excerpt_separator: <!--more-->

# Front Matter defaults
defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: post
      author: Carl Vuorinen
      comments: true

include:
  - _redirects

plugins:
  - jekyll-gist
