# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Cvuorinen.net
description: Dev notes & thoughts about PHP and web development
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://cvuorinen.net" # the base hostname & protocol for your site
twitter_username: cvuorinen
github_username:  cvuorinen

# Build settings
markdown: kramdown
highlighter: pygments
permalink: /:year/:month/:title/
excerpt_separator: <!--more-->
